# Generated by Django 4.2.30 on 2026-05-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('Musique', 'Musique'), ('Tech & Innovation', 'Tech & Innovation'), ('Sports', 'Sports'), ('Arts', 'Arts'), ('Autre', 'Autre')], default='Autre', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='filiere',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Filière'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos/'),
        ),
    ]
