# Generated by Django 4.2.30 on 2026-05-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_category_user_filiere_alter_club_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Salle', 'Salle'), ('Amphithéâtre', 'Amphithéâtre'), ('Salle Socioculturelle', 'Salle Socioculturelle')], default='Salle', max_length=50, verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='event_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure'),
        ),
        migrations.AddField(
            model_name='eventrequest',
            name='location',
            field=models.CharField(choices=[('Salle', 'Salle'), ('Amphithéâtre', 'Amphithéâtre'), ('Salle Socioculturelle', 'Salle Socioculturelle')], default='Salle', max_length=50, verbose_name='Lieu'),
        ),
    ]
