# Generated by Django 4.2.30 on 2026-05-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_event_event_time_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(choices=[('Salle 12', 'Salle 12'), ('Salle 22', 'Salle 22'), ('Salle 35', 'Salle 35'), ('Amphithéâtre', 'Amphithéâtre'), ('Salle Socioculturelle', 'Salle Socioculturelle')], default='Salle 12', max_length=50, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='eventrequest',
            name='location',
            field=models.CharField(choices=[('Salle 12', 'Salle 12'), ('Salle 22', 'Salle 22'), ('Salle 35', 'Salle 35'), ('Amphithéâtre', 'Amphithéâtre'), ('Salle Socioculturelle', 'Salle Socioculturelle')], default='Salle 12', max_length=50, verbose_name='Lieu'),
        ),
    ]
